# Generated by Django 5.2.5 on 2025-08-20 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('application_date', models.DateField()),
                ('job_title', models.CharField(max_length=255)),
                ('job_posting', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('interview1', 'Interview 1'), ('interview2', 'Interview 2'), ('interview3', 'Interview 3'), ('interview4', 'Interview 4'), ('interview5', 'Interview 5'), ('offer', 'Offer'), ('rejected', 'Rejected')], default='applied', max_length=20)),
                ('max_stage', models.CharField(choices=[('acknowledgment', 'Acknowledgment'), ('interview1', 'Interview 1'), ('interview2', 'Interview 2'), ('interview3', 'Interview 3'), ('interview4', 'Interview 4'), ('interview5', 'Interview 5'), ('offer', 'Offer'), ('rejected', 'Rejected')], default='acknowledgment', max_length=20)),
                ('last_update', models.DateField(auto_now=True)),
            ],
        ),
    ]
