# Generated by Django 5.2.5 on 2025-08-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationentry',
            name='max_stage',
            field=models.CharField(choices=[('none', 'None'), ('acknowledgment', 'Acknowledgment'), ('interview1', 'Interview 1'), ('interview2', 'Interview 2'), ('interview3', 'Interview 3'), ('interview4', 'Interview 4'), ('interview5', 'Interview 5'), ('offer', 'Offer'), ('rejected', 'Rejected')], default='acknowledgment', max_length=20),
        ),
    ]
