# Generated by Django 5.2.5 on 2025-09-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_applicationentry_max_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationentry',
            name='expected_response_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
