# Generated by Django 5.2.5 on 2025-09-01 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_applicationentry_expected_response_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationentry',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
